### PR TITLE
Test on new Ruby versions

### PR DESCRIPTION
**Pull request by nicolasleger**
Add Ruby 2.5 and use patched versions from Travis.

### CODE REVIEW

**Comment by lucascaton** [comment]
Hey @tenderlove - I noticed the build has been failing for a while (in `master` branch). So can we get this one merged, please? And release a new version to support Ruby 2.5 on Windows?

Please let me know if I can help :)
Cheers!

**Comment by lucascaton** [comment]
cc: @luislavena

**Comment by lucascaton** [comment]
Any news on this?

**Comment by MSP-Greg** [comment]
@lucascaton

Re Windows builds, I opened a PR for PowerShell code that generates a fat binary gems while testing on Appveyor.  Both 32 & 64 support Ruby 2.0 thru 2.5.  64 bit also has a trunk build.

32 bit & 64 bit gems are stored as artifacts, see https://ci.appveyor.com/project/MSP-Greg/sqlite3-ruby/build/2.  Test logs also saved as artifacts.  Note that it is built with SQLite 3.24.0.

Feel free to download and test, etc.

Greg

**Pull request merged**
