### PR TITLE
feat: allow URI filenames

### PR DESCRIPTION
**Pull request by flavorjones**
See https://www.sqlite.org/uri.html

### CODE REVIEW

**Comment by flavorjones** [comment]
I think it might be better to not merge this -- the `Open::URI` bit can be passed where people want to pass a URI, and all the options available via URI are also available via the API.

What I really want is to be able to inject configuration options in a Rails app via the `config/database.yml` and so maybe it's better for me to do some work in the Rails sqlite3 adapter instead.

**Comment by flavorjones** [comment]
Yeah, going to move this decision to Rails.

**Comment by flavorjones** [comment]
Hrm, reopening.

**Comment by flavorjones** [comment]
FWIW, it looks like the major distros compile with `-DSQLITE_USE_URI=1`, also (e.g. debian has compiled with it since 2019 / 3.27.1-1).

**Comment by tenderlove** [comment]
Ah, I didn't realize this was a feature natively supported by SQLite.  Yes, we should do this.

**Pull request merged**
