### PR TITLE
Adds --with-sqlcipher flag

### PR DESCRIPTION
**Pull request by WA9ACE**
Adds automatic support for compiling with sqlcipher to allow for encrypted database support.

Also adds a top-level eh? method to check if sqlite3 was installed/compiled with sqlcipher support.

### CODE REVIEW

**Comment by WA9ACE** [comment]
Build passed on all rubies but head. Head test environment didn't install sqlite.

**Comment by gazayas** [comment]
Interesting! I haven't seen an implementation of this in the gem itself, so I wonder what the moderators might think of this.
I know I'm not a moderator of this repository, so I don't know if this'll carry any weight...
But I thought changing the method name to `using_sqlcipher_p` for the c method and `using_sqlcipher?` for the ruby method would help to make it in line with the style of the other `?` methods (like `closed_p` `db.closed?` in `database.c`).

**Comment by padde** [comment]
@WA9ACE thanks for this. Do you happen to have example code for how to connect to sqlcipher from Ruby?

**Comment by WA9ACE** [comment]
@padde sure! I'll try to put up a blog post this weekend on how to decrypt a sqlcipher database and query it with this.

**Comment by WA9ACE** [comment]
@padde Here's a quick little tutorial on using sqlcipher from ruby with some example code. Let me know if you have any trouble! https://wa9ace.net/2019/08/24/how-to-query-sqlcipher-encrypted-databases-with-ruby.html

**Comment by padde** [comment]
@WA9ACE  thank you! Very kind of you to put together a blog post. Now I understand how the pieces fit together. Have a good one!

**Comment by michaelpulis** [comment]
Hi! I am trying to install use sqlcipher on Ruby, on Linux. Ruby, sqlite3 and sqlcipher are all installed on this machine.
I tried the following command:
`gem install -- --with-sqlcipher`

As well as the following command:
`gem install sqlite3 -- --with-sqlcipher-dir=/opt/sqlcipher/`

where /opt/sqlcipher/ is the path where sqlcipher is installed. This does not result in an error, but then the example cited on your website, written in ruby, gives the following error when trying to parse an encrypted .db file:
 `initialize': file is encrypted or is not a database (SQLite3::NotADatabaseException)
The file was opened using sqlcipher normally frrom the terminal without any issues.

Do you have any idea why I can't get ruby to work with sqlcipher?

Thanks :)

**Pull request merged**
