### PR TITLE
Updated the methods for pragma calls according to the currently

### LINKED ISSUE #120: Missing pragmas
There are several pragmas which do not have wrappers in `pragma.rb`.

http://sqlite.org/pragma.html

The one I noticed was `journal_mode`.

### PR DESCRIPTION
**Pull request by aibor**
Some of the pragmas called in the Pragmas module were deprecated and new ones were missing.
So I updated the methods for pragma calls according to the currently supported pragmas listed on https://sqlite.org/pragma.html
This should fix #120

### CODE REVIEW

**Comment by tenderlove** [comment]
Honestly I'm not a huge fan of supporting all of these since they change from version to version.  It means we have to keep updating them as upstream adds more.  Could we consider just providing methods to get and set pragmas, and people can pass in the pragma name they care about?  Then we don't have to keep updating this stuff and I think it would be more clear to the user, and they can manipulate pragmas without waiting for us to upgrade our API.

**Comment by aibor** [comment]
I absolutely agree that keeping the pragma methods up to date is tedious. As the different pragma type getter and setter methods are already there, it might be desirable to make them public. So if one of the wrappers is outdated because the usage has changed or new pragmas have been added, anyone can use the generic getters and setters for these pragmas.
But I think there is no point in throwing the already present wrappers over board. At least for enum pragmas I consider them rather valuable.

**Comment by tenderlove** [comment]
> As the different pragma type getter and setter methods are already there, it might be desirable to make them public. So if one of the wrappers is outdated because the usage has changed or new pragmas have been added, anyone can use the generic getters and setters for these pragmas.

I agree.

> But I think there is no point in throwing the already present wrappers over board. At least for enum pragmas I consider them rather valuable.

I agree with this as well.  Can you change the PR to just make those getter / setter methods public?

**Comment by aibor** [comment]
Type based getters/setters have been made public with ae6c84a.

I have also added methods for recently added pragmas. In order to keep the keep it tidy I have squashed the commits regarding these wrapper methods into ee010db, which is based on current master, now.

I'm sorry for the mess, but I hope this will keep the commit log sane.

**Comment by tenderlove** [comment]
@aibor great, thank you!

**Pull request merged**
